# Generated by Django 4.2.6 on 2023-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
