# Generated by Django 4.2.6 on 2023-10-23 15:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_rename_name_categorie_nom_rename_name_image_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='cat',
            new_name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='desc',
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
