# Generated by Django 4.2.6 on 2023-10-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_rename_cat_produit_categorie_remove_produit_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='img',
            new_name='image_couverture',
        ),
    ]
