# Generated by Django 4.2.6 on 2023-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image: 1200x700'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image: 1200x700'),
        ),
    ]
