# Generated by Django 4.2.6 on 2023-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='numero',
            new_name='numero_de_commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='message',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
