# Generated by Django 4.2.6 on 2023-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_rename_numero_commande_numero_de_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.SlugField(default='ref 1'),
            preserve_default=False,
        ),
    ]
