# Generated by Django 4.2.6 on 2023-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_produit_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='traiter',
            field=models.BooleanField(default=False),
        ),
    ]
