# Generated by Django 4.2.6 on 2023-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
