# Generated by Django 4.2.6 on 2023-11-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_image_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
