# Generated by Django 4.2.6 on 2023-11-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_create_at_service_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image_couverture',
            new_name='image',
        ),
    ]
