# Generated by Django 4.2.6 on 2023-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_rename_img_membre_photo_membre_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='specialite',
            field=models.CharField(default='rien', max_length=300),
            preserve_default=False,
        ),
    ]
