# Generated by Django 4.2.6 on 2023-11-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0004_alter_membre_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseaux',
            name='nom',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X')], max_length=255),
        ),
    ]
