# Generated by Django 4.2.6 on 2023-11-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0006_specialiter_alter_membre_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.specialiter'),
        ),
    ]
