# Generated by Django 4.2.6 on 2023-10-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('repondu', models.BooleanField()),
            ],
        ),
    ]
