# Generated by Django 4.2.6 on 2023-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nom',
            new_name='nom_prenom',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='prenom',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='dfdf@dfd.df', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='sujet',
            field=models.CharField(default='d', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='repondu',
            field=models.BooleanField(default=False),
        ),
    ]
