# Generated by Django 4.2.6 on 2023-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='cour_description',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(upload_to='1699611472.539941'),
        ),
    ]
