# Generated by Django 4.2.6 on 2023-11-10 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formation', '0002_formation_cour_description_alter_categorie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='message',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='numero_telephone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.AddField(
            model_name='client',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(upload_to='1699626305.2802362'),
        ),
    ]
