# Generated by Django 4.2.6 on 2023-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(blank=True, max_length=200, null=True)),
                ('sujet', models.CharField(blank=True, max_length=300, null=True, verbose_name='Quartier / ville')),
                ('date_rendezvous', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
