# Generated by Django 4.2.6 on 2023-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='sujet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sujet'),
        ),
    ]
