# Generated by Django 4.2.6 on 2023-11-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='courte_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
